### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by ZippyMagician** [TeamIlluminati/overwatch-lfg-discord-bot#1]
What isn't working?

**Comment by TeamIlluminati** [comment]
I'm not sure. I have to load it up into my VPS to test it.  I'm busy right now so it may be in a few days or so.

**Comment by ZippyMagician** [comment]
Ok i figured everything that was wronge

**Comment by ZippyMagician** [comment]
- Typos
- Invalid package.json(name, etc)
- Invalid token manager
- Weird in general

Fixed all of it
