### ISSUE TITLE
LET IT GROW

### ISSUE THREAD

**Issue by ZippyMagician** [TeamIlluminati/overwatch-lfg-discord-bot#2]
You don't know me but names Sai
I'm just the O'Hare delivery guy
But it seems like trees might be worth a try
So I say let it grow
My name is Dan, and my name's Rose
Our son Wesley kind of glows
And that's not good so we suppose
We should let it grow
Let it grow
Let it grow
You can't reap what you don't sow
Plant a seed inside the earth
Just one way to know it's worth
Let's celebrate the world's rebirth
We say let it grow
My name's Marie and I am 3
I was born into slavery
Lalalalalalee
I say let it grow
I'm granny Norma I'm old and I got grey hair
But I remember when trees were everywhere
And no one had to pay for air
So I say let it grow
Let it grow
Let it grow
Like it did so long ago
Maybe it's just one tiny seed
But it's all we really need
It's time to change the life we lead
Time to let it grow
My name's O'Hare
I'm one of you
I live here in Thneedville too
The things you say just might be true
It could be time to start anew
And maybe change my point of view
Nah! I say let it die
Let it die, let it die
Let it shrivel up and die
Come one who's with me huh?
Nobody.
You greedy dirt bag!
Let it grow
Let it grow
Let the love inside ya show
Plant a seed inside the earth
Just one way to know it's worth
Let's celebrate the world's rebirth
We say let it grow
Let it grow
Let it grow
You can't reap what you don't sow
It's just one tiny seed
But it's all we really need
It's time to banish all your greed
Imagine Thneedville flowered and treed
Let this be our solemn creed
We say let it grow (x4)

**Comment by TeamIlluminati** [comment]
Closed.

**Comment by ZippyMagician** [comment]
lmao
